version: '3.5'
services:
  node:
    build: .
    environment:
      - PORT=3004
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
    ports:
      - 3004:3004
    volumes:
      - .:/app/
      - /app/node_modules/
      - /app/deploy/
    networks:
      - my-network

networks:
  my-network:
    name: ubademy
    driver: bridge